spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphql_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
graphql:
  tools:
    schema-location-pattern: "**/*.graphql"